### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bobkocisko** [DeutscheSoft/aux-widgets#1]
Hello!  Thank you for this awesome library.  

The documentation states that this repository can be installed with npm.  However...

`npm install --save @deutschesoft/aux-widgets`

Gives this output
```text
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@deutschesoft%2faux-widgets - Not found
npm ERR! 404
npm ERR! 404  '@deutschesoft/aux-widgets@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Which leads me to believe that installation via npm requires direct github access

`npm install --save https://github.com/DeutscheSoft/aux-widgets`

Is that correct?

**Comment by boomshop** [comment]
Hey @bobkocisko 

what kind of terminal/OS are you using? It should work as written in the first command line. Maybe you have to add quotes around the package name?

Kind regards
Markus
