### ISSUE TITLE
Moving the grid labels of a chart outside the area

### ISSUE THREAD

**Issue by MatthiasMann** [DeutscheSoft/aux-widgets#6]
I'm trying to prevent the graph lines in a chart from overlapping with the grid labels.

Like applying a padding to the chart but without it affecting the labels.
I tried a few things but so far it seems I would have to write my own chart/graph widget to be able to do that.

**Comment by arneg** [comment]
Hi Matthias,

yes, I think there might be no way to do that with the chart currently. Could you post a screenshot here for us to better understand the issue?

**Comment by MatthiasMann** [comment]
This is the style guide from our designers:
![image](https://github.com/user-attachments/assets/80e8bae4-f19e-4f3d-af55-a289e3687dfc)

And this is what I currently can create:
![image](https://github.com/user-attachments/assets/a611352a-f6d9-40e3-91ab-7c9316bcccc1)
(I seem to have forgotten to add the border …)

**Comment by boomshop** [comment]
You could put Scales next to and underneath Chart.
